name: Generate Snake 

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - id: generate
      uses: Platane/snk@master
      with:
        github_user_name: purna16
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg
    
    - run: |
        echo "gif_path=${gif_out_path}" >> $GITHUB_ENV
        echo "svg_path=${svg_out_path}" >> $GITHUB_ENV

    - uses: crazy-max/ghaction-github-pages@v3
      with: 
        target_branch: output
        build_dir: ${git_path}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
